const PokemonsActionTypes = {
  FETCH_POKEMONS_START: "FETCH_POKEMONS_START",
  FETCH_POKEMONS_SUCCESS: "FETCH_POKEMONS_SUCCESS",
  FETCH_POKEMONS_FAILURE: "FETCH_POKEMONS_FAILURE",
  SEARCH_POKEMONS: 'SEARCH_POKEMONS',
};

export default PokemonsActionTypes;
